name: maeeen
description: Maeeen - Your Spiritual Companion on the Path of Worship.
publish_to: 'Maeeen Inc' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#==== Dependencies start ====#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  intl: ^0.19.0
  http: ^1.1.0
  path: ^1.8.3
  http_parser: ^4.0.2
  hijri: ^3.0.0
  vibration: ^1.8.3
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  sqflite: ^2.3.0
  flutter_timezone: ^1.0.7
  prayers_times: ^0.0.6
  share: ^2.0.4
  permission_handler: ^10.4.5
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_qiblah: ^2.2.0
  razorpay_flutter: ^1.3.7
  flutter_paypal: ^0.2.1
  flutter_stripe: ^11.0.0
  flutter_paystack_plus: ^2.0.4
  shimmer: ^3.0.0



  just_audio: ^0.9.39

  # just_audio: ^0.9.38
  # path_provider: ^2.1.3

#==== Dev Dependencies start ====#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

#==== Assets start ====#
  assets:
    - assets/icon/
    - assets/icon/flag/
    - assets/language/
    - assets/audio/
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/font/ElMessiri-Regular.ttf
          weight: 400
        - asset: assets/font/ElMessiri-Medium.ttf
          weight: 300
        - asset: assets/font/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/font/ElMessiri-Bold.ttf
          weight: 700